name: countdown_calendar
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  path_provider: ^2.0.8
  image_picker: ^0.8.4+4
  shared_preferences: ^2.0.11

flutter:

  uses-material-design: true

  assets:
    - assets/images/background1.jpg

  fonts: 
    - family: Rajdhani
      fonts: 
      - asset: assets/fonts/Rajdhani-Medium.ttf